---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confworkload
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: confidentialworkload
          image: dacrookregistry.azurecr.io/conf_test:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: regcred